version: '3.7'

services: 

  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment: 
      POSTGRES_URI: postgres://renatoamreis:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports: 
      - "3000:3000"

  # Postgres - We don't need container_name as it will take image name
  postgres:
    environment: 
      POSTGRES_USER: renatoamreis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # REDIS Service
  redis: 
    image: redis
    ports:
      - "6379:6379" 